field: 3499b21e-9ea5-4d82-a599-e2bea3bf5ee9
fieldLayouts:
  b16aff06-e392-47fe-86ce-59828c25ff49:
    tabs:
      -
        elements:
          -
            fieldUid: 574616ad-ec2f-48d8-94bd-ffee0e13fcc5
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: a6ecdd6d-c840-44d2-b78e-e0741bbf1218
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: bee032b5-590d-4e99-adc4-f3a5282a3754
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 56a2da6e-1c89-42cf-bbfc-5f69ab9b2039
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
fields:
  56a2da6e-1c89-42cf-bbfc-5f69ab9b2039:
    contentColumnType: string
    fieldGroup: null
    handle: portfolioPage
    instructions: 'which portfolio page is this image linked to?'
    name: 'Portfolio Page'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Choose an entry'
      showSiteMenu: true
      source: null
      sources:
        - 'section:3c179024-6729-4830-9212-395ff84a3aad'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  574616ad-ec2f-48d8-94bd-ffee0e13fcc5:
    contentColumnType: string
    fieldGroup: null
    handle: imageFile
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:ed7a90f0-b4e5-4c4c-b15c-831c22754213'
      defaultUploadLocationSubpath: '{owner.slug}'
      limit: '1'
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:ed7a90f0-b4e5-4c4c-b15c-831c22754213'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  a6ecdd6d-c840-44d2-b78e-e0741bbf1218:
    contentColumnType: string
    fieldGroup: null
    handle: size
    instructions: ''
    name: Size
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - small
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - medium
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Half
            -
              - value
              - half
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - large
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  bee032b5-590d-4e99-adc4-f3a5282a3754:
    contentColumnType: string
    fieldGroup: null
    handle: spacing
    instructions: ''
    name: Spacing
    searchable: false
    settings:
      multi: true
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - none
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Top
            -
              - value
              - spacing-top
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - spacing-left
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - spacing-right
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Bottom
            -
              - value
              - spacing-bottom
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\MultiSelect
handle: image
name: Image
sortOrder: 1
