field: d8038199-6ebf-4559-89fe-1ed2c749551f
fieldLayouts:
  5e3f54ff-f129-4b4c-8d73-a9c490bd3980:
    tabs:
      -
        elements:
          -
            fieldUid: de3e3a12-41ca-4577-b8bc-e5bb486dd628
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9646efc0-6d57-4bf1-9340-391b1c151f68
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4df982d1-5de1-44a2-a173-5a66e4d29522
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4df982d1-5de1-44a2-a173-5a66e4d29522:
    contentColumnType: text
    fieldGroup: null
    handle: penEmbed
    instructions: ''
    name: 'Pen Embed'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: ''
      redactorConfig: ''
      removeEmptyTags: ''
      removeInlineStyles: ''
      removeNbsp: ''
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  9646efc0-6d57-4bf1-9340-391b1c151f68:
    contentColumnType: string(255)
    fieldGroup: null
    handle: penUrl
    instructions: ''
    name: 'Pen Url'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  de3e3a12-41ca-4577-b8bc-e5bb486dd628:
    contentColumnType: text
    fieldGroup: null
    handle: penTitle
    instructions: ''
    name: 'Pen Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: pen
name: Pen
sortOrder: 1
