app: craft3-tib7
ssh_url: craft3-tib7@deploy.us1.frbit.com
git_remote: craft3-tib7/master
before:
    code/up: {  }
after:
    code/down:
        - 'php craft migrate/all'
        - 'php craft project-config/apply'
