context: global
field: 09d7205f-7433-426c-9841-55969fd31a37
fieldLayout:
  792b0c96-581f-47c2-b438-b609113e5ae4:
    tabs:
      -
        fields:
          d28106b9-6f6f-45f0-ad60-8a1b1dc0dee6:
            required: false
            sortOrder: 1
        name: Image
        sortOrder: 1
      -
        fields:
          57f2a55a-7cf2-4402-8f5b-736c80aa951c:
            required: false
            sortOrder: 2
          c8ed6671-af7a-44a5-9cbc-f26ac19a65e4:
            required: false
            sortOrder: 1
        name: Settings
        sortOrder: 2
groupName: Blocks
groupSortOrder: '1'
matrixBlockType: ac2a163a-ec9d-4e8c-9ba8-37f7b109ffb6
sortOrder: '1'
