context: global
field: 09d7205f-7433-426c-9841-55969fd31a37
fieldLayout:
  d2a75375-2450-4937-9aec-ca67d9c53417:
    tabs:
      -
        fields:
          0da5fedc-87b4-49da-9c82-4b81ab09e122:
            required: false
            sortOrder: 1
        name: Text
        sortOrder: 1
      -
        fields:
          92575ff2-cb6c-46c4-a3b0-c07b75d30b09:
            required: false
            sortOrder: 2
          cd6404f5-f145-4a24-b1c3-a349c4803ccf:
            required: false
            sortOrder: 1
        name: Settings
        sortOrder: 2
groupName: Blocks
groupSortOrder: '1'
matrixBlockType: 53c6741b-e13f-4d0a-97ce-6255a0325304
sortOrder: '2'
