contentColumnType: text
fieldGroup: e6c2f5c4-186f-4fab-87bc-d11cbe3d0707
handle: description
instructions: 'A short description displayed on the stories landing page'
name: Description
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
