contentColumnType: string
fieldGroup: 5aeab9d2-b4b3-452c-a6d0-7ab33429580e
handle: images
instructions: ''
name: Images
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:ed7a90f0-b4e5-4c4c-b15c-831c22754213'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Add an image'
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:ed7a90f0-b4e5-4c4c-b15c-831c22754213'
  singleUploadLocationSubpath: '{owner.slug}'
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
