dateModified: 1661295458
email:
  fromEmail: matt.m.soria@gmail.com
  fromName: mattsoria
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0a36206a-cf43-4e78-9b99-0cc7f90c30a0: 'Public Schema' # Public Schema
    3a31e72a-88e2-4200-ad77-ebad59464e3a: Seo # Seo
    010b5339-42ae-49c2-a832-d120abafd2d2: Tagline # Tagline
    50bafd98-bc33-405b-a6e8-fe28dae9fb59: '404 Page' # 404 Page
    82173ec0-2aaf-4f12-9405-8d9bc00da7ec: 'Web Schema' # Web Schema
    35815072-acac-4452-9c5d-768772bc4940: 'Matt Soria' # Matt Soria
plugins:
  assetrev:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  easymde-markdown-editor:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  embeddedassets:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  imager:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  matrixtoolbar:
    edition: standard
    enabled: true
    schemaVersion: 1.0.4
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  sitemap:
    edition: standard
    enabled: true
    schemaVersion: 1.0.2
  smith:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  webhooks:
    edition: standard
    enabled: true
    schemaVersion: 2.4.0
system:
  edition: pro
  live: true
  name: mattsoria
  schemaVersion: 3.7.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
