enableVersioning: true
handle: photography
name: Photography
propagationMethod: all
siteSettings:
  35815072-acac-4452-9c5d-768772bc4940:
    enabledByDefault: true
    hasUrls: true
    template: photography
    uriFormat: '{slug}'
structure:
  maxLevels: null
  uid: ce1365bc-875c-499f-82fe-d9e32958f59c
type: structure
