enableVersioning: false
handle: socialLinks
name: 'Social Links'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  35815072-acac-4452-9c5d-768772bc4940:
    enabledByDefault: true
    hasUrls: true
    template: ''
    uriFormat: 'social-links/{slug}'
structure:
  maxLevels: null
  uid: b536dc83-9132-44e5-8fba-db93495d0fb4
type: structure
