enableVersioning: true
handle: storiesLandingPage
name: 'Stories Landing Page'
propagationMethod: all
siteSettings:
  35815072-acac-4452-9c5d-768772bc4940:
    enabledByDefault: true
    hasUrls: true
    template: stories
    uriFormat: stories
type: single
